---
title: "Programming Assignment 3 : Hospital Comparison"
author: "Somaya AlGabry"
date: "24/11/2020"
output: pdf_document
---
## For more details about this assignment, please read: [assignment details](https://github.com/Somaya-AlGabry/Hospital-Compare/blob/main/Assignment%20datails.pdf)

```{r setup, include= TRUE, echo= TRUE}
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
```

# 1. Plot the 30-day mortality rates for heart attack:
```{r plot, include=TRUE, echo= TRUE}
 outcome[, 11] <- as.numeric(outcome[, 11])
 hist(outcome[, 11], main = "Hospital 30 Day Death Mortality Rates from Heart Attack",
      xlab= "Motrality Rate")
 
```

# 2. Finding the best hospital in a state:

``` {r best, include = TRUE , echo= TRUE}
best <- function(state, outcome) {
  #Read data:
  ocdata <- read.csv("outcome-of-care-measures.csv", colClasses = "character",
    na.strings = NA , stringsAsFactors =  FALSE)

  
  #check that arguments are valid:
  if (!state %in% ocdata$State) {
    stop("invalid state")
  }
  
  if (outcome == "heart attack") {
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack" 
  } else if (outcome =="heart failure"){
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure"
  } else if (outcome == "pneumonia") {
    colname = "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia"
  } else {
    stop ("invalid outcome")
  }
  
  #order data:
  
  ocdata2 <- subset(ocdata, State == state, select = c("Hospital.Name", colname ))
  ocdata2[,colname] <- as.numeric(ocdata2[,colname]) 
  ocdata2 <- ocdata2[order(ocdata2[,2], ocdata2[,1]),]
  ocdata2 <- na.omit(ocdata2)
  
  #return hospital name:
   ocdata2[1, 1]
   
}

#Examples: 
source("best.R")
best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")


```

3. Ranking hospitals by outcome in a state:

``` {r rankhospital, include= TRUE, echo= TRUE}
rankhospital <- function(state, outcome, num = "best") {
  #Read data:
  ocdata <- read.csv("outcome-of-care-measures.csv", colClasses = "character", 
  na.strings = NA , stringsAsFactors =  FALSE)
  
  
  #check that arguments are valid:
  if (!state %in% ocdata$State) {
    stop("invalid state")
  }
  
  if (outcome == "heart attack") {
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack" 
  } else if (outcome =="heart failure"){
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure"
  } else if (outcome == "pneumonia") {
    colname = "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia"
  } else {
    stop ("invalid outcome")
  }
  
  #order data:
 
  ocdata2 <- subset(ocdata, State == state, select = c("Hospital.Name", colname ))
  ocdata2[,colname] <- as.numeric(ocdata2[,colname]) 
  ocdata2 <- ocdata2[order(ocdata2[,2], ocdata2[,1]),]
  ocdata2 <- na.omit(ocdata2)
  
  #return hospital name:
  if (num == "best") {
    ocdata2[1,1]
  }
  else if (num == "worst" ){
    ocdata2[nrow(ocdata2),1]
  }
  else {
    ocdata2[num, 1]
  }

}

#Examples:
source("rankhospital.R")
 rankhospital("TX", "heart failure", 4)
 rankhospital("MD", "heart attack", "worst")
 rankhospital("MN", "heart attack", 5000)
```

4.  Ranking hospitals in all states:

``` {r rankall, include= TRUE, echo= TRUE}
rankall <- function(outcome, num = "best") {
  #Read data:
  ocdata <- read.csv("outcome-of-care-measures.csv", colClasses = "character", 
  na.strings = NA , stringsAsFactors =  FALSE)
  
  
  #check that outcome is valid:
  
  if (outcome == "heart attack") {
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack" 
  } else if (outcome =="heart failure"){
    colname= "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure"
  } else if (outcome == "pneumonia") {
    colname = "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia"
  } else {
    stop ("invalid outcome")
  }
  
  #order data:
  
  ocdata2 <- subset(ocdata, select = c("Hospital.Name", "State", colname ))
  ocdata2[,colname] <- as.numeric(ocdata2[,colname]) 
  ocdata2 <- ocdata2[order(ocdata2$State, ocdata2[,3], ocdata2$Hospital.Name),]
  ocdata2 <- na.omit(ocdata2)
  
  #split data acc to state:
  ocdata3 <- split(ocdata2, ocdata2$State)
  
  #find the hospital with rank "num" in each state:
  hospital_Name <- sapply(ocdata3, function(elt, num = "best"){
    if (num == "best") {
      elt[1,1]
    }
    else if (num == "worst" ){
      elt[length(elt),1]
    }
    else  {
     elt[num,1]
    }
    
  } , num)
  
  # create data frame consists of the hospital name with rank num and the state 
df <- as.data.frame(hospital_Name, names(ocdata3))
df2 <- cbind(df, names(ocdata3))
colnames(df2)<- c("Hospital Name", "State")
df2
}

#Examples:
 source("rankall.R")
 head(rankall("heart attack", 20), 10)
 tail(rankall("pneumonia", "worst"), 3)
tail(rankall("heart failure"), 10)
```